### ISSUE TITLE
Add ability to check miqsel version

### ISSUE THREAD

**Issue by valaparthvi** [digitronik/miqsel#2]
Currently, there's no option to check miqsel version, it'll be nice to check the version with something like `miqsel --version`.

**Comment by digitronik** [comment]
humm,
you can add just simple default `click` `version` decorator... `@click.version_option()` on entry point. 

```
@click.version_option()
@click.group()
@connection
def cli(connection):
```

**Comment by valaparthvi** [comment]
Great, I'll do that!
