### ISSUE TITLE
YAMLLoadWarning while loading yml file 

### ISSUE THREAD

**Issue by ganeshhubale** [digitronik/miqsel#22]
- Getting warning - ```YAMLLoadWarning``` while loading yml file data
- Warning:
```
(n) [ghubale@localhost miqsel]$ miqsel appliance
/home/ghubale/g/miqsel/miqsel/config.py:17: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(ymlfile)
```
- This warning should be avoided.
For more information click [here](https://github.com/digitronik/miqsel/pull/3#discussion_r277159134)

**Comment by digitronik** [comment]
fixed in https://github.com/digitronik/miqsel/pull/25
