### ISSUE TITLE
Echo vnc and command executor urls

### ISSUE THREAD

**Issue by digitronik** [digitronik/miqsel#4]
Simple command to print/echo `command_executor` and `vnc`. so we can use same thing for other projects.
it will return...
command_executor:
`http://172.17.0.2:4444/wd/hub`

vnc:
`http://172.17.0.2:5999`

**Comment by sbulage** [comment]
I will work on it.

**Comment by sbulage** [comment]
@digitronik you want to print VNC and Command_executor, in the start method or you want it under viewer method .?
